In [1]:
import numpy as np

In [4]:
np_array_1 = np.array([1, 2, 3, 4])

print(np_array_1)
print(type(np_array_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [26]:
np_array_2 = np.array([[1, 2, 3], [4, 5, 6]])

print(np_array_2)

[[1 2 3]
 [4 5 6]]


In [6]:
# 0 행렬

zero_array = np.zeros((3, 4))

print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# 1로 채워진 행렬

one_array = np.ones((3, 3))

print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
full_array = np.full((3, 4), 5)

print(full_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [10]:
eye_array = np.eye(5)

print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
random_array = np.random.random((3, 3))

print(random_array)

[[0.63126813 0.63983301 0.78538717]
 [0.1086912  0.81645323 0.30528438]
 [0.19554897 0.32748448 0.89269383]]


In [13]:
arange_array = np.arange(10)

print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
reshape_array = arange_array.reshape((2, 5))

print(reshape_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
# 정렬 연산

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [17]:
# 행렬의 합

print(x + y)
print(np.add(x, y))

[5 7 9]
[5 7 9]


In [18]:
# 행렬의 차

print(x - y)
print(np.subtract(x, y))

[-3 -3 -3]
[-3 -3 -3]


In [19]:
# 행렬의 곱

print(x * y)
print(np.multiply(x, y))

[ 4 10 18]
[ 4 10 18]


In [20]:
# 행렬의 나누기

print(x / y)
print(np.divide(x, y))

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [22]:
# 행렬의 행렬곱

x2 = np.array([[1, 2], [3, 4]])
y2 = np.array([[5, 6], [7, 8]])

In [24]:
print(x2 @ y2)
print(np.dot(x2, y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
